theme: jekyll-theme-dinky
title: "cleanNLP"
description: R package providing a set of fast tools for converting a textual corpus into a set of normalized tables.
  Users may make use of a Python backend with 'spaCy' or the Java backend 'CoreNLP'.
show_downloads: false
